### ISSUE TITLE
Tun interface causing issues when starting exaproxy

### ISSUE THREAD

**Issue by piotrkotowski** [Exa-Networks/exaproxy#35]
Hello,
 there seems to be an issue related to presence of tun interface (needed i.e. by openvpn) which results in error:

```
-- Traceback


Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/exaproxy-1.2.1/lib/exaproxy/util/debug.py", line 71, in <module>
    execfile(sys.argv[0])
  File "/home/user/exaproxy-1.2.1/lib/exaproxy/application.py", line 306, in <module>
    main()
  File "/home/user/exaproxy-1.2.1/lib/exaproxy/application.py", line 276, in main
    Supervisor(configuration).run()
  File "/home/user/exaproxy-1.2.1/lib/exaproxy/supervisor.py", line 131, in __init__
    self.interfaces()
  File "/home/user/exaproxy-1.2.1/lib/exaproxy/supervisor.py", line 211, in interfaces
    for interface in getifaddrs():
  File "/home/user/exaproxy-1.2.1/lib/exaproxy/util/interfaces.py", line 233, in getifaddrs
    sa = sockaddr.from_address(ifa.ifa_addr)
TypeError: integer expected
```

It looks very similiar to https://github.com/ros/ros_comm/issues/30 .

When the tun* interface is gone (openvpn stopped) exaproxy starts normally.

Thanks for fixing problem!

**Comment by thomas-mangin** [comment]
Thank you for the report. We have been busy recently and this bug went unnoticed. Could you please help us by adding on line 232 print type(ifa.ifa_addr).

**Comment by thomas-mangin** [comment]
Looking at the code, we already seem to be checking for the case where the address is None.

**Comment by piotrkotowski** [comment]
I have added f.write within' while loop (starting at interfaces.py:233), because print result didn't show up on the console nor in the exaproxy log file. 
I think it's pretty strange, because the output was:
<type 'int'>

**Comment by thomas-mangin** [comment]
We will try to replicate.
