### ISSUE TITLE
crash when Control/Worker Control/Debug

### ISSUE THREAD

**Issue by limbo127** [Exa-Networks/exaproxy#41]
In web interface, click on Control/xxxx crash server : 
Host: 52.49.155.160:800\r\n
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0\r\n
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\n
Accept-Language: en-US,en;q=0.5\r\n
Accept-Encoding: gzip, deflate\r\n
Connection: keep-alive\r\n
Upgrade-Insecure-Requests: 1\r\n
\r\n
]]
ExaProxy 20589  header        parsing header [[GET /favicon.ico HTTP/1.1\r\n
Host: 52.49.155.160:800\r\n
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0\r\n
Accept: */*\r\n
Accept-Language: en-US,en;q=0.5\r\n
Accept-Encoding: gzip, deflate\r\n
Connection: keep-alive\r\n
\r\n
]]
ExaProxy 20567  client        cleanup for socket <socket._socketobject object at 0x7fdd54f378a0>
ExaProxy 20589  header        parsing header [[GET /favicon.ico HTTP/1.1\r\n
Host: 52.49.155.160:800\r\n
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0\r\n
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\n
Accept-Language: en-US,en;q=0.5\r\n
Accept-Encoding: gzip, deflate\r\n
Connection: keep-alive\r\n
\r\n
]]
ExaProxy 20589  header        parsing header [[GET /control/workers.html HTTP/1.1\r\n
Host: 52.49.155.160:800\r\n
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0\r\n
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\n
Accept-Language: en-US,en;q=0.5\r\n
Accept-Encoding: gzip, deflate\r\n
Referer: http://52.49.155.160:800/\r\n
Connection: keep-alive\r\n
Upgrade-Insecure-Requests: 1\r\n
\r\n
]]

--------------------------------------------------------------------------------
-- Please provide the information below on :
-- http://code.google.com/p/exaproxy/issues/entry
--------------------------------------------------------------------------------

-- Version

2.7.12 (default, Sep  1 2016, 22:14:00) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]

-- Logging History

Fri, 25 Nov 2016 08:36:11 supervisor error         Starting exaproxy version 1.2.1
Fri, 25 Nov 2016 08:36:11 supervisor error         python version 2.7.12 (default, Sep  1 2016, 22:14:00)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Fri, 25 Nov 2016 08:36:11 supervisor debug         starting /tmp/exaproxy-master/lib/exaproxy/application.py
Fri, 25 Nov 2016 08:36:11 daemon critical      WARNING: python remote execution via the web server is enabled
Fri, 25 Nov 2016 08:36:11 daemon info          for information, your configuration requires 65728 available file descriptors
Fri, 25 Nov 2016 08:36:11 supervisor info          the chosen polling reactor was epoll
Fri, 25 Nov 2016 08:36:11 server info          server [http proxy] accepting up to 32768 clients
Fri, 25 Nov 2016 08:36:11 server info          server [web server] accepting up to 2 clients
Fri, 25 Nov 2016 08:36:11 supervisor info          found new local ip 127.0.0.1 (lo)
Fri, 25 Nov 2016 08:36:11 supervisor info          found new local ip 172.16.1.53 (eth0)
Fri, 25 Nov 2016 08:36:11 supervisor info          found new local ip ::1 (lo)
Fri, 25 Nov 2016 08:36:11 supervisor info          found new local ip fe80::3d:f2ff:fe8b:5f11 (eth0)
Fri, 25 Nov 2016 08:37:35 client debug         cleanup for socket <socket._socketobject object at 0x7fdd54f378a0>

-- Traceback

Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/exaproxy-master/lib/exaproxy/util/debug.py", line 71, in <module>
    execfile(sys.argv[0])
  File "/tmp/exaproxy-master/lib/exaproxy/application.py", line 327, in <module>
    main()
  File "/tmp/exaproxy-master/lib/exaproxy/application.py", line 297, in main
    Supervisor(configuration).run()
  File "/tmp/exaproxy-master/lib/exaproxy/supervisor.py", line 270, in run
    status, events = self.reactor.run()
  File "/tmp/exaproxy-master/lib/exaproxy/reactor/reactor.py", line 355, in run
    self.enactDecisions(decisions)
  File "/tmp/exaproxy-master/lib/exaproxy/reactor/reactor.py", line 290, in enactDecisions
    response, length, status, buffer_change = self.content.getContent(client, command, decision)
  File "/tmp/exaproxy-master/lib/exaproxy/reactor/content/manager.py", line 255, in getContent
    content = ('close', http('200', self.page.html(path)))
  File "/tmp/exaproxy-master/lib/exaproxy/html/page.py", line 446, in html
    return menu(self._workers())
  File "/tmp/exaproxy-master/lib/exaproxy/html/page.py", line 279, in _workers
    'exaproxy.redirector.minimum' : self.supervisor.manager.low,
AttributeError: 'Supervisor' object has no attribute 'manager'

--------------------------------------------------------------------------------
-- Please provide the information above on :
-- http://code.google.com/p/exaproxy/issues/entry
--------------------------------------------------------------------------------

**Comment by thomas-mangin** [comment]
Hello - Sorry for the late answer. Could you please use master as we fixed quite a number of issue and have not yet released 1.2.2
